# Generated by Django 3.0.4 on 2020-04-04 12:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('alignment', models.CharField(choices=[('Left', 'Left Alignment (e.g. English)'), ('Right', 'Right Alignment (e.g. Persian, Arabic, Urdu, etc)')], max_length=50)),
                ('version', models.CharField(default='v', max_length=10)),
            ],
        ),
    ]
