# Generated by Django 3.0.4 on 2020-04-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='alignment',
            field=models.CharField(choices=[('left', 'Left (e.g. English)'), ('right', 'Right (e.g. Persian, Arabic, Urdu, etc)')], help_text="\nYou may use Persian language.\nDon't forget to set the direction from the top corner of content editor.\n", max_length=50),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='version',
            field=models.CharField(max_length=50),
        ),
    ]
