# Generated by Django 3.0.4 on 2020-03-28 14:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='t1',
        ),
        migrations.AddField(
            model_name='documentation',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Content'),
        ),
    ]
