# Generated by Django 3.0.4 on 2020-03-28 14:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20200328_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
    ]
