# Generated by Django 3.0.4 on 2020-04-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20200404_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pe', 'Persian')], default='en', max_length=5),
        ),
    ]
