# Generated by Django 3.0.4 on 2020-03-28 14:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20200328_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='version',
            field=models.CharField(default='v', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
